[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]


[formatter.lua]
command = "stylua"
includes = ["*.lua"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
  "*.css",
  "*.html",
  "*.js",
  "*.json",
  "*.jsx",
  "*.md",
  "*.mdx",
  "*.scss",
  "*.ts",
  "*.yaml",
]

[formatter.toml]
command = "taplo"
options = ["format", "$@"]
includes = ["*.toml"]


[formatter.shell]
command = "sh"
options = ["-eucx", """
# Perform static analysis tool
shellcheck --external-sources --source-path=SCRIPTDIR "$@"

# Run formatter
shfmt --write --simplify --case-indent --indent 4 "$@"
    """, "--"]
includes = ["*.sh"]
